### ISSUE TITLE
backpack and OCS

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/backpack#6]
For some OCS tests, I want to run the workload pods on separate physical machines from the OCS (OpenShift Container Storage) cluster - I think this is a problem that other folks might have too, with more than OCS.  At present, backpack will be blissfully unaware that there are other nodes involved in the test and will not collect metadata about them.  It would be great if there was a way to hand backpack a list of labels that mean "collect metadata about any of the nodes that have one of these labels".    For example, OCS nodes are all labelled.   Doing it this way would make it applicable to much more than just OCS.

**Comment by dry923** [comment]
@bengland2 I have created PR https://github.com/cloud-bulldozer/ripsaw/pull/335 which would allow you to run the metadata daemonset on only specifically labeled nodes. You would have to run it in addition to the normal fio/etc cr. Something as simple as this would work for nodes labeled foo=bar

```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: backpack
  namespace: my-ripsaw
spec:
  elasticsearch:
    server: es_server
    port: 9200
  metadata:
    collection: true
    targeted: false
    label_name: foo
    label_value: bar
  workload:
    name: metadata
```

**Comment by bengland2** [comment]
looks good to me, just have to try it out.   1 label is probably enough.

**Comment by dry923** [comment]
If needed i could probably make it loop on a list but I haven't tried that with it yet

**Comment by dry923** [comment]
@bengland2 I updated the PR to take a list of labels. Let me know your thoughts.

The cr would now look like:

```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: backpack
  namespace: my-ripsaw
spec:
  elasticsearch:
    server: "marquez.perf.lab.eng.rdu2.redhat.com"
    port: 9200
  metadata:
    collection: true
    targeted: false
    label:
      - [ 'my', 'bar' ]
      - [ 'foo', 'bar' ]
  workload:
    name: metadata
```

The node(s) would have to match all the labels given as its an implied AND functionality.
